title: "Workshop SynBio 2025"
author: "Jennyfer Arismendiz y equipo"
logo: images/logot.svg   # Crea luego una carpeta 'images' con tu logo
html:
  favicon: images/favicon.svg
  extra_css: [custom.css]   # ⬅️ Añadiremos este archivo en el siguiente paso
  theme:
    name: sphinx_book_theme
    options:
      path_to_docs: "."
      repository_url: https://github.com/polarbio/wsynbio-2025
      use_repository_button: true
      use_issues_button: true
      navigation_with_keys: true
