
title: Workshop SynBio 2025
author: Laboratorio del Dr. Christian Cuba Samaniego
logo: images/logot.svg
favicon: images/favicon.svg

only_build_toc_files: true

repository:
  url: https://github.com/polarbio/wsynbio-2025
  path_to_book: ""
  branch: main

html:
  extra_navbar: Notas del Workshop SynBio 2025
  extra_footer: Hecho con ❤️ por RELU.
  extra_css:
    - _static/custom.css

theme:
  name: sphinx_book_theme
  options:
    home_page_in_toc: true
    show_navbar_depth: 2
    show_toc_level: 2
    use_repository_button: true
    repository_url: https://github.com/polarbio/wsynbio-2025
    repository_branch: main
